### ISSUE TITLE
La selection des shards depasse des bords du formulaire

### ISSUE THREAD

**Issue by Tetrastorm** [GuillaumeCa/circus-pes#3]
### Environnement technique

Plateforme:
- Ubuntu 20.04LTS

Navigateur:
- Mozilla Firefox 108.0.1

### Etapes de reproduction
 
- Se connecter sur le site
- Créer une "nouvelle creation"
- Constater la presence du bug d'UI

### Evidence

![Screenshot 2023-01-06 at 11-39-04 Circus PES](https://user-images.githubusercontent.com/24191367/210992764-e13a8770-ec3d-4bc9-9b16-20708282c840.png)

### Information complémentaire

- Ce produit quand plus de 6 shardid sont enregistrés par le site.

**Comment by Faucon-Noir** [comment]
Problème présent également sur OpéraGX et Chrome (dernière version stable)
Systèmes windows 10 et 11 (edition famille comme pro)
